DROP TABLE IF EXISTS FILMS CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS FILM_GENRE CASCADE;
DROP TABLE IF EXISTS MPA CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS FILM_LIKE CASCADE;
DROP TABLE IF EXISTS FRIENDS CASCADE;

CREATE TABLE PUBLIC.MPA (
	ID INTEGER NOT NULL,
	RATE VARCHAR_IGNORECASE(10) NOT NULL,
	CONSTRAINT MPA_PK PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.FILMS (
	NAME CHARACTER VARYING(40) NOT NULL,
	DESCRIPTION CHARACTER VARYING(40) NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	MPA INTEGER,
	RATE INTEGER,
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CONSTRAINT FILMS_PK PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.GENRE (
	ID INTEGER NOT NULL,
	NAME VARCHAR_IGNORECASE(20) NOT NULL ,
	CONSTRAINT GENRE_PK PRIMARY KEY (ID)
);
CREATE TABLE PUBLIC.FILM_GENRE (
	ID_FILMS INTEGER NOT NULL AUTO_INCREMENT,
	ID_GENRE INTEGER NOT NULL
);
CREATE TABLE PUBLIC.USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING(40) NOT NULL,
	LOGIN CHARACTER VARYING(40) NOT NULL,
	NAME CHARACTER VARYING(40) NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (ID),
	BIRTHDAY DATE NOT NULL
);
CREATE TABLE PUBLIC.FILM_LIKE (
	ID_FILMS INTEGER NOT NULL,
	ID_USER INTEGER NOT NULL
);
CREATE TABLE PUBLIC.FRIENDS (
	ID_USER1 INTEGER NOT NULL ,
	ID_USER2 INTEGER NOT NULL ,
	STATUS_1 BOOLEAN
);

ALTER TABLE FILMS
ADD CONSTRAINT mpa_fk FOREIGN KEY(mpa) REFERENCES MPA(id) ON DELETE CASCADE;
ALTER TABLE FILM_GENRE
ADD CONSTRAINT fg_fk FOREIGN KEY(ID_FILMS) REFERENCES FILMS(id) ON DELETE CASCADE;
ALTER TABLE FILM_GENRE
ADD CONSTRAINT g_fk FOREIGN KEY(ID_GENRE) REFERENCES GENRE(id) ON DELETE CASCADE;
ALTER TABLE FILM_LIKE
ADD CONSTRAINT fl_fk FOREIGN KEY(ID_FILMS) REFERENCES FILMS(id) ON DELETE CASCADE;
ALTER TABLE FILM_LIKE
ADD CONSTRAINT u_fk FOREIGN KEY(ID_USER) REFERENCES USERS(id) ON DELETE CASCADE;

ALTER TABLE FRIENDS
ADD CONSTRAINT u1_fk  FOREIGN KEY(ID_USER1) REFERENCES USERS(id) ON DELETE CASCADE;
ALTER TABLE FRIENDS
ADD CONSTRAINT u2_fk  FOREIGN KEY(ID_USER2) REFERENCES USERS(id) ON DELETE CASCADE;
